[env]
TERM = "xterm-256color"

[window]
opacity=0.95

[font]
size = 14

[font.bold]
family = "FiraCode Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "FiraCode Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "FiraCode Nerd Font Mono"
style = "Italic"

[font.normal]
family = "FiraCode Nerd Font Mono"
style = "Regular"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Super|Shift"

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = false

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 5
y = 5

[colors.primary]
background = "#FFFFFF"
foreground = "#343434"

[colors.cursor]
text = "CellBackground"
cursor = "#6F6F6F"

[colors.normal]
black = "#C4C4C4"
red = "#FF0000"
green = "#008000"
yellow = "#795E26"
blue = "#0000FF"
magenta = "#AF00DB"
cyan = "#16825D"
white = "#343434"

[colors.bright]
black = "#E5E5E5"
red = "#A31515"
green = "#098658"
yellow = "#800000"
blue = "#007ACC"
magenta = "#AF00DB"
cyan = "#16825D"
white = "#FFFFFF"
