[env]
TERM = "xterm-256color"

[font]
size = 13

[font.bold]
family = "FiraCode Nerd Font"
style = "Bold"

[font.bold_italic]
family = "FiraCode Nerd Font"
style = "Bold Italic"

[font.italic]
family = "FiraCode Nerd Font"
style = "Italic"

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Super|Shift"

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = false

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 5
y = 5

[colors.primary]
background = '#300a24'
foreground = '#eeeeec'

# 0x Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = '#bbbbbb'
cursor = '#b4d5ff'

# 0x Normal colors
[colors.normal]
black   = '#2e3436'
red     = '#cc0000'
green   = '#4e9a06'
yellow  = '#c4a000'
blue    = '#3465a4'
magenta = '#75507b'
cyan    = '#06989a'
white   = '#d3d7cf'

# 0x Bright colors
[colors.bright]
black   = '#555753'
red     = '#ef2929'
green   = '#8ae234'
yellow  = '#fce94f'
blue    = '#729fcf'
magenta = '#ad7fa8'
cyan    = '#34e2e2'
white   = '#eeeeec'

[[keyboard.bindings]]
key = "Return"
mods = "Shift"
chars = "\u001B\r"
